script:
  name: "Configure IP Addresses"
  description: "Enhanced IP address configuration with CLI support, validation, and logging"
  category: "system"
  subcategory: "networking"
  
  file: "configure_ip.sh"
  requires_root: true
  estimated_duration: "1-3 minutes"
  
  cli_shortcuts:
    - "config-ip"
    - "ip"
    - "configure-ip"
  keywords:
    - "ip"
    - "address"
    - "configure"
    - "interface"
    - "network"
    - "static"
    - "add"
    - "remove"
    - "flush"
  
  parameters:
    - name: "interface"
      type: "interface"
      description: "Network interface to configure"
      required: false
    - name: "operation"
      type: "choice"
      description: "Configuration operation"
      required: false
      default: "interactive"
      validation:
        choices:
          - value: "add"
            description: "Add IP address"
          - value: "remove"
            description: "Remove IP address"
          - value: "flush"
            description: "Flush all IP addresses"
          - value: "interactive"
            description: "Interactive mode"
    - name: "ip_address"
      type: "ip_address"
      description: "IP address with CIDR notation"
      required: false
      validation:
        pattern: '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/[0-9]+$'
  
  dependencies:
    tools:
      - name: "ip"
        package: "iproute2"
        check_command: "which ip"
      - name: "grep"
        package: "grep"
        check_command: "which grep"
  
  output:
    creates_files: false
    workspace_subdirs: []
    logs_operations: true
  
  tags:
    - "networking"
    - "configuration"
    - "ip-address"
    - "interface"
    - "enhanced"
    - "validation"
    - "logging"
  risk_level: "medium"
  network_access: false
  modifies_system: true
  
  examples:
    - description: "Interactive IP configuration"
      command: "netutil config-ip"
    - description: "Add IP address directly"
      command: "./configure_ip.sh -i eth0 -a 192.168.1.100/24"
    - description: "Remove IP address directly"
      command: "./configure_ip.sh -i eth0 -r 192.168.1.100/24"
    - description: "Flush all addresses from interface"
      command: "./configure_ip.sh --flush eth0"
  
  version: "2.0"
  author: "fortifyde"
  last_updated: "2025-01-20"