script:
  name: "Configure IP Addresses (Enhanced)"
  description: "Enhanced IP address configuration with comprehensive validation and logging"
  category: "system"
  subcategory: "networking"
  
  file: "configure_ip_improved.sh"
  requires_root: true
  estimated_duration: "1-3 minutes"
  
  cli_shortcuts:
    - "ip-enhanced"
    - "config-ip-v2"
  keywords:
    - "ip"
    - "address"
    - "configure"
    - "interface"
    - "networking"
    - "enhanced"
  
  parameters:
    - name: "interface"
      type: "interface"
      description: "Network interface to configure"
      required: false
    - name: "operation"
      type: "choice"
      description: "Operation to perform"
      required: false
      validation:
        choices:
          - value: "add"
            description: "Add IP address"
          - value: "remove"
            description: "Remove IP address"
          - value: "flush"
            description: "Flush all IP addresses"
    - name: "ip_address"
      type: "ip_address"
      description: "IP address with CIDR notation"
      required: false
      validation:
        pattern: '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/[0-9]+$'
  
  dependencies:
    tools:
      - name: "ip"
        package: "iproute2"
        check_command: "which ip"
      - name: "grep"
        package: "grep"
        check_command: "which grep"
    scripts:
      - "../common/logging.sh"
      - "../common/utils.sh"
      - "../common/validation.sh"
  
  output:
    creates_files: false
    workspace_subdirs: []
  
  tags:
    - "ip-configuration"
    - "networking"
    - "interface-management"
    - "enhanced"
    - "security"
  risk_level: "medium"
  network_access: false
  modifies_system: true
  
  examples:
    - description: "Interactive IP configuration"
      command: "netutil ip-enhanced"
    - description: "Add IP address directly"
      command: "netutil ip-enhanced -i eth0 -a 192.168.1.100/24"
    - description: "Remove IP address"
      command: "netutil ip-enhanced -i eth0 -r 192.168.1.100/24"
    - description: "Flush all addresses"
      command: "netutil ip-enhanced --flush eth0"
  
  version: "2.0"
  author: "NetUtility Team"
  last_updated: "2025-01-18"